### ISSUE TITLE
Failing build: missing `runnable` folder?

### ISSUE THREAD

**Issue by mindplay-dk** [catamphetamine/country-flag-icons#2]
After cloning and running `npm install`, I get the following error:

```
> country-flag-icons@1.0.5 generate-countries /home/mindplay/workspace/country-flag-icons
> babel-node runnable/generate-countries

internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '/home/mindplay/workspace/country-flag-icons/runnable/generate-countries'
```

The `runnable` folder seems to be missing from source-control?

(This project looks fantastic, by the way! Every other flag package has some flags with way too much detail, inconsistent file sizes or dimensions etc. - it must have been quite a bit of work to curate this package... I'd like to contribute another build-script, one that inlines all the SVG images in a single CSS file to avoid the JavaScript overhead of the React component...)

**Comment by catamphetamine** [comment]
Github website was having status 500 errors and didn't accept comments.

@mindplay-dk Thx, removed `runnable` from `.gitignore`.

**Comment by catamphetamine** [comment]
> it must have been quite a bit of work to curate this package...

Not really, initially.
But I'll be redrawing most of the flags a little bit.
